import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Toaster} from 'react-hot-toast'
import Header from "./components/Header";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en"  suppressHydrationWarning>
        
        <body
         
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-900 text-white`}
        >
          <Header/>
          <main className=""> 
            <div>
              {children}
            </div>
         </main>
         

     
        <Toaster  />
        </body>
       
      </html>
    </ClerkProvider>
  );
}
